services:
  - type: web
    name: flegm-frontend
    env: node
    region: frankfurt
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /
    healthCheckTimeout: 5
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        value: https://flegm-api.onrender.com
      - key: NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME
        value: dfupyozxe
      - key: NEXT_PUBLIC_CLOUDINARY_API_KEY
        value: 165535318843775
    scaling:
      minInstances: 1
      maxInstances: 1
      targetMemoryPercent: 80
    buildFilter:
      paths:
        - frontend/**/*.tsx
        - frontend/**/*.ts
        - frontend/package*.json 