services:
  - type: web
    name: flegm
    env: node
    region: Oregon
    plan: starter
    buildCommand: |
      cd backend
      yarn global add @types/node@22.13.1
      yarn install --frozen-lockfile --production=false --ignore-workspace-root-check
      yarn add -D @types/node@22.13.1
      yarn build
    startCommand: cd backend && NODE_ENV=production node dist/server.js
    healthCheckPath: /api/health
    healthCheckTimeout: 10
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: MONGODB_URI
        sync: true
      - key: JWT_SECRET
        sync: true
      - key: CLOUDINARY_CLOUD_NAME
        sync: true
      - key: CLOUDINARY_API_KEY
        sync: true
      - key: CLOUDINARY_API_SECRET
        sync: true
      - key: SESSION_SECRET
        sync: true
      - key: FRONTEND_URL
        value: https://flegm.fr
      - key: API_URL
        value: https://flegm.onrender.com
      - key: FACEBOOK_APP_ID
        sync: true
      - key: FACEBOOK_APP_SECRET
        sync: true
      - key: GOOGLE_CLIENT_ID
        sync: true
      - key: GOOGLE_CLIENT_SECRET
        sync: true
      - key: TIKTOK_CLIENT_KEY
        sync: true
      - key: TIKTOK_CLIENT_SECRET
        sync: true
      - key: REDIS_URL
        sync: true
      - key: LOG_LEVEL
        value: info
    scaling:
      minInstances: 1
      maxInstances: 1
      targetMemoryPercent: 80
    headers:
      - path: /*
        name: Strict-Transport-Security
        value: max-age=31536000; includeSubDomains
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
    disk:
      name: tmp
      mountPath: /tmp
      sizeGB: 1 