services:
  - type: web
    name: flegm
    env: node
    region: Oregon
    buildCommand: cd backend && NODE_ENV=production yarn install --ignore-scripts && yarn build
    startCommand: cd backend && yarn start
    healthCheckPath: /api/health
    healthCheckTimeout: 5
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: MONGODB_URI
        sync: true
      - key: JWT_SECRET
        sync: true
      - key: CLOUDINARY_CLOUD_NAME
        value: dfupyozxe
      - key: CLOUDINARY_API_KEY
        sync: true
      - key: CLOUDINARY_API_SECRET
        sync: true
      - key: FRONTEND_URL
        value: https://flegm.fr
    scaling:
      minInstances: 1
      maxInstances: 1
      targetMemoryPercent: 80
    buildFilter:
      paths:
        - backend/**/*.js
        - backend/**/*.ts
        - backend/package*.json 