services:
  - type: web
    name: flegm-api
    env: node
    region: frankfurt  # Choisissez la région la plus proche
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false  # À configurer dans le dashboard Render
      - key: JWT_SECRET
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        value: dfupyozxe
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: FRONTEND_URL
        value: https://flegm.vercel.app  # URL de production du frontend
    autoDeploy: true 
        value: 8080 