name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Debug environment
        run: |
          pwd
          ls -la
          cd frontend
          ls -la
          node --version
          npm --version

      - name: Install Dependencies
        working-directory: frontend
        run: |
          echo "Cleaning npm cache..."
          npm cache clean --force
          echo "Removing existing node_modules and package-lock.json..."
          rm -rf node_modules package-lock.json
          echo "Installing dependencies..."
          npm install --no-package-lock --no-audit --no-fund --loglevel=error
          echo "Listing installed packages..."
          npm ls --depth=0

      - name: Build
        working-directory: frontend
        env:
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
          NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME: ${{ secrets.NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME }}
          NEXT_PUBLIC_CLOUDINARY_API_KEY: ${{ secrets.NEXT_PUBLIC_CLOUDINARY_API_KEY }}
          NODE_OPTIONS: "--max_old_space_size=4096"
        run: |
          echo "Starting build process..."
          echo "Checking Next.js config:"
          cat next.config.js
          echo "\nChecking package.json:"
          cat package.json
          echo "\nStarting build:"
          npm run build
          echo "\nBuild completed, checking output:"
          ls -la .next

      - name: Export
        working-directory: frontend
        run: |
          echo "Starting export process..."
          npm run export
          echo "\nCreating .nojekyll file..."
          touch out/.nojekyll
          echo "\nChecking exported files:"
          ls -la out
          echo "nicogaray7.github.io" > out/CNAME

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: frontend/out
          clean: true
          cname: nicogaray7.github.io 