name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Debug environment
        run: |
          pwd
          ls -la
          cd frontend
          ls -la
          node --version
          npm --version

      - name: Install Dependencies
        working-directory: frontend
        env:
          NODE_OPTIONS: "--max-old-space-size=4096"
        run: |
          echo "Nettoyage du cache npm..."
          npm cache clean --force
          echo "Installation des dépendances..."
          npm ci --prefer-offline --no-audit --no-fund
          echo "Liste des paquets installés..."
          npm ls --depth=0

      - name: Build
        working-directory: frontend
        env:
          NODE_OPTIONS: "--max-old-space-size=4096"
        run: |
          echo "Démarrage du build..."
          echo "Configuration Next.js :"
          cat next.config.js
          echo "\nPackage.json :"
          cat package.json
          echo "\nDémarrage du build :"
          npm run build
          echo "\nBuild terminé, vérification de la sortie :"
          ls -la .next

      - name: Export
        working-directory: frontend
        run: |
          echo "Démarrage de l'export..."
          npm run export
          echo "\nCréation du fichier .nojekyll..."
          touch out/.nojekyll
          echo "\nVérification des fichiers exportés :"
          ls -la out

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: frontend/out
          clean: true
          cname: nicogaray7.github.io 