name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Debug environment
        run: |
          echo "Current directory:"
          pwd
          echo "\nRoot directory contents:"
          ls -la
          echo "\nFrontend directory contents:"
          ls -la frontend
          echo "\nNode.js version:"
          node --version
          echo "\nNPM version:"
          npm --version

      - name: Install Dependencies
        working-directory: frontend
        run: |
          npm install --legacy-peer-deps
          npm ls --depth=0

      - name: Build
        working-directory: frontend
        env:
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
          NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME: ${{ secrets.NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME }}
          NEXT_PUBLIC_CLOUDINARY_API_KEY: ${{ secrets.NEXT_PUBLIC_CLOUDINARY_API_KEY }}
          NODE_OPTIONS: "--max_old_space_size=4096"
        run: |
          npm run build

      - name: Export
        working-directory: frontend
        run: |
          npm run export
          touch out/.nojekyll
          ls -la out
          echo "nicogaray7.github.io" > out/CNAME

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: frontend/out
          clean: true
          cname: nicogaray7.github.io 