name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    container: 
      image: node:20-alpine
      options: --user root

    steps:
      - name: Install system dependencies
        run: |
          apk add --no-cache git python3 make g++

      - name: Checkout
        uses: actions/checkout@v3

      - name: List directory contents
        run: ls -la frontend

      - name: Install Dependencies
        working-directory: ./frontend
        run: |
          npm install --no-optional --no-shrinkwrap --no-package-lock

      - name: Build
        working-directory: ./frontend
        run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/out
        env:
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
          NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME: ${{ secrets.NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME }}
          NEXT_PUBLIC_CLOUDINARY_API_KEY: ${{ secrets.NEXT_PUBLIC_CLOUDINARY_API_KEY }} 