name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.11.0'

      - name: List files
        run: |
          pwd
          ls -la
          ls -la frontend/

      - name: Install Dependencies
        working-directory: frontend
        run: |
          echo "Node version: $(node -v)"
          echo "NPM version: $(npm -v)"
          npm install --legacy-peer-deps --verbose
          npm list --depth=0

      - name: Build
        working-directory: frontend
        run: |
          echo "Starting build..."
          npm run build
          echo "Build completed"
          ls -la .next/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: frontend/.next
          enable_jekyll: false
        env:
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
          NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME: ${{ secrets.NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME }}
          NEXT_PUBLIC_CLOUDINARY_API_KEY: ${{ secrets.NEXT_PUBLIC_CLOUDINARY_API_KEY }} 